# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nginx:
  replicaCount: 1
  image:
    repo: huckchen0422/hiskio-gitops
    tag: 6c6a065
  pullPolicy: Always
  prefix: webhook-demo
hook: true
